### ISSUE TITLE
Incorrect Graph Legend (Under the heading "Finding the Svelte Bundle Size Formula")?

### ISSUE THREAD

**Issue by Acmion** [halfnelson/svelte-it-will-scale#1]
The graph under the heading "Finding the Svelte Bundle Size Formula" seems to have an incorrect legend. The "minified" and "original" should be switched, since the minified should not be larger than original.

**Comment by halfnelson** [comment]
Believe it or not, the minified "compiled" source is actually larger than
the original. The compiled source is 4x larger than the original, the
minified version of the compiled source is almost twice the original
source, it needs to be gzipped before it is smaller at all

**Comment by Acmion** [comment]
How is this possible? Could you provide the files for inspection, for example, under a "data" directory? 

What would the result be if you just gzipped the original then? Would it be less than gzip + minification?

**Comment by halfnelson** [comment]
You can see this size increase from compiling by going to svelte.dev/repl
and using the js tab on the right to see the compiled component source and
comparing, svelte adds in the reactivity and drags in some helpers from
svelte/internal which increases the size

**Comment by Acmion** [comment]
I understand that the components grow after Svelte processes them.

So in this analysis, "Original" = size of the entire "src" directory? 

The confusion might be caused by the fact that usually when doing JS development we have these following stages:
1. Source JS file, which could be called "Original"
2. Minified JS file, which could be called "Minified"
3. Gzipped minified JS file, which could be called "Gzip + Min"

**Comment by halfnelson** [comment]
Yes, we have:

1. Original - .svelte file size
2. Compiled - .js size after svelte compilation
3. Minified - js size after minification
4. Min+gzip - zipped size of minified JS

I left compiled off the chart since it was 430% larger than original and
ruined the scale of the vertical axis

**Comment by Acmion** [comment]
Hmm,

I had a go at this myself (still in progress). 

Check the methodology here:
[https://github.com/Acmion/SvelteScaling](https://github.com/Acmion/SvelteScaling)

The results here:
[https://acmion.github.io/SvelteScaling/](https://acmion.github.io/SvelteScaling/)

 Our slopes for Svelte are similar, but the differences in intercepts is quite large.

**Comment by joaopaulobdac** [comment]
Am I correct thinking that since [preact is 4kb](https://bundlephobia.com/result?p=preact@10.5.7) and [react-dom is 39.4kb](https://bundlephobia.com/result?p=react-dom@17.0.1) (minified+gzipped), the svelte inflection point against preact is actually at about 8kb or so of component source size? I'm just subtracting 40kb from the bundle size of the graph here https://svelte-scaling.acmion.com/and then seeing where the svelte bundle size would intersect.

**Comment by joaopaulobdac** [comment]
In fact, subtracting 35.4kb from the [react formula](https://github.com/halfnelson/svelte-it-will-scale/blob/master/README.md#calculating-the-inflection-point) gives an inflection point of 15.5kb. Am I correct here?

**Comment by lillallol** [comment]
@Acmion 

When `x = 0` then `y` has to give the bundle size of the framework. Your intercepts have to be exactly the same. If they are not, then consider the following two cases:

1. Someone is doing linear regression without taking the intercept as a known.
2. Someone is using different version of React or Svelte and hence different bundle size.

**Comment by Acmion** [comment]
@lillallol 

Yes, the different intercepts is most likely caused by different versions.

However, the initial issue here was that the fact that in this analysis the size of "minified" is greater than of "original". This does not intuitively make sense and I initially misunderstood the meaning of these. If the labels were changed to "minified" and "source", then everything would be clear.
